[package]
name = "terrain"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_panorbit_camera = "0.19.3"
indicatif = "0.17.8"
noise = "0.9.0"
rand = { version = "0.8.5", features = ["small_rng"] }
